Refactor
SFDO-Sprint-2019-Philadelphia/DeclarativeTestGeneration pull request #12
Opened 2023-09-30 06:52 UTC by selfuntitled

# Critical Changes
Removed dependency on custom metadata type, remains in package for run as user configuration
Refactored to execute flows based upon naming convention - test_ prefix.

# Changes
Move original POC code into separate class. 
Removed failed effort to include metata api library to deploy apex dynamically. 

# Issues Closed

2023-10-02 18:54 UTC, allisonletts requested changes
- "Success" condition should not be case sensitive.
- Ideally, test output should name the tested flow
- Documentation: make sure the "result" variable is marked for output from the flow.

2023-10-03 05:39 UTC, selfuntitled commented
Success condition is no longer case sensitive
Flow names appear in expected result when test fails
Flow names appear in debug log
Opened exec slots for up to 100 test flows
Added performance optimization to decrease query count by 50%

2023-10-04 18:50 UTC, allisonletts approved these changes

2023-10-04 18:51 UTC, allisonletts approved these changes

2023-10-04 18:52 UTC, allisonletts approved these changes

2023-10-06 16:13 UTC, allisonletts approved these changes

2023-10-06 16:14 UTC, allisonletts approved these changes
Works as expected. Thanks for the updates!

2023-10-30 21:21 UTC, merged